#!/usr/bin/env python3
"""
Export the EthioMorph repository into a single Markdown file for external
tools (LLM context, code review, documentation generators, etc.).

Usage:
    python3 scripts/export_codebase.py
    python3 scripts/export_codebase.py -o my_export.md
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "CODEBASE_EXPORT.md"

# Paths relative to repo root (globs supported via rglob where noted)
INCLUDE_FILES = [
    "README.md",
    "requirements.txt",
    "vercel.json",
    "main.py",
    "src/*.py",
    "api/**/*.py",
    "tests/*.py",
    "web/index.html",
    "web/favicon.svg",
    "data/stems.json",
    "data/templates.json",
    "data/lexicon.json",
    "paper/ethiomorph_paper.tex",
    "paper/Makefile",
]

LANG_BY_SUFFIX = {
    ".py": "python",
    ".json": "json",
    ".html": "html",
    ".svg": "xml",
    ".tex": "latex",
    ".md": "markdown",
    "": "text",
}


def _expand_patterns() -> list[Path]:
    seen: set[Path] = set()
    paths: list[Path] = []

    for pattern in INCLUDE_FILES:
        if any(ch in pattern for ch in "*?[]"):
            for match in sorted(ROOT.glob(pattern)):
                if match.is_file():
                    resolved = match.resolve()
                    if resolved not in seen:
                        seen.add(resolved)
                        paths.append(match)
        else:
            path = ROOT / pattern
            if path.is_file():
                resolved = path.resolve()
                if resolved not in seen:
                    seen.add(resolved)
                    paths.append(path)

    return paths


def _language(path: Path) -> str:
    return LANG_BY_SUFFIX.get(path.suffix.lower(), "text")


def _rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def build_export(paths: list[Path]) -> str:
    lines = [
        "# EthioMorph — Full Codebase Export",
        "",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "Single-file bundle of source, API handlers, web UI, data, tests, and paper.",
        "Do not edit this file by hand; regenerate with `python3 scripts/export_codebase.py`.",
        "",
        "## Table of Contents",
        "",
    ]

    for path in paths:
        rel = _rel(path)
        anchor = rel.replace("/", "-").replace(".", "-").lower()
        lines.append(f"- [{rel}](#{anchor})")

    lines.append("")
    lines.append("---")
    lines.append("")

    for path in paths:
        rel = _rel(path)
        lang = _language(path)
        content = path.read_text(encoding="utf-8")

        lines.append(f"## `{rel}`")
        lines.append("")
        lines.append(f"```{lang}")
        lines.append(content.rstrip("\n"))
        lines.append("```")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Export repo to one Markdown file")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output path (default: {DEFAULT_OUTPUT.name})",
    )
    args = parser.parse_args()

    paths = _expand_patterns()
    if not paths:
        raise SystemExit("No files matched export patterns.")

    output = args.output if args.output.is_absolute() else ROOT / args.output
    output.write_text(build_export(paths), encoding="utf-8")

    total_lines = sum(1 for _ in output.open(encoding="utf-8"))
    print(f"Wrote {output} ({len(paths)} files, ~{total_lines:,} lines)")


if __name__ == "__main__":
    main()
